"""initial schema

Revision ID: f199ced7abac
Revises: 
Create Date: 2026-07-21 03:31:59.448004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f199ced7abac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('linux_servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('fqdn', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('operating_system', sa.String(length=100), nullable=True),
    sa.Column('os_version', sa.String(length=100), nullable=True),
    sa.Column('kernel_version', sa.String(length=150), nullable=True),
    sa.Column('cpu_count', sa.Integer(), nullable=True),
    sa.Column('cpu_model', sa.String(length=255), nullable=True),
    sa.Column('ram_gb', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_ansible_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('linux_servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_linux_servers_environment_id'), ['environment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_linux_servers_hostname'), ['hostname'], unique=True)
        batch_op.create_index(batch_op.f('ix_linux_servers_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_linux_servers_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_linux_servers_owner_id'), ['owner_id'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=150), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['linux_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_server_id'), ['server_id'], unique=False)

    op.create_table('patching',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('patch_status', sa.String(length=50), nullable=False),
    sa.Column('current_kernel', sa.String(length=150), nullable=True),
    sa.Column('previous_kernel', sa.String(length=150), nullable=True),
    sa.Column('last_patch_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reboot_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pending_updates', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['linux_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patching', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patching_server_id'), ['server_id'], unique=True)

    op.create_table('server_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['linux_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'package_id', name='uq_server_package')
    )
    with op.batch_alter_table('server_packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_server_packages_package_id'), ['package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_server_packages_server_id'), ['server_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server_packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_server_packages_server_id'))
        batch_op.drop_index(batch_op.f('ix_server_packages_package_id'))

    op.drop_table('server_packages')
    with op.batch_alter_table('patching', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patching_server_id'))

    op.drop_table('patching')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_server_id'))

    op.drop_table('notes')
    with op.batch_alter_table('linux_servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_linux_servers_owner_id'))
        batch_op.drop_index(batch_op.f('ix_linux_servers_location_id'))
        batch_op.drop_index(batch_op.f('ix_linux_servers_ip_address'))
        batch_op.drop_index(batch_op.f('ix_linux_servers_hostname'))
        batch_op.drop_index(batch_op.f('ix_linux_servers_environment_id'))

    op.drop_table('linux_servers')
    op.drop_table('packages')
    op.drop_table('owners')
    op.drop_table('locations')
    op.drop_table('environments')
    # ### end Alembic commands ###
