"""add reboot_required to patching

Revision ID: f2483460adc8
Revises: efe97b87aab7
Create Date: 2026-07-21 13:05:45.501185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2483460adc8'
down_revision = 'efe97b87aab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patching', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reboot_required', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patching', schema=None) as batch_op:
        batch_op.drop_column('reboot_required')

    # ### end Alembic commands ###
